import { Component } from '@angular/core';
import { STORE_CONFIG } from '../../core/store.config';

@Component({ selector: 'app-contact', standalone: true, template: `
  <section class="page-shell contact-page"><span class="eyebrow text-olive">Estamos cerca</span><h1 class="font-editorial">Hablemos de<br/><em>tu próximo look.</em></h1><p class="lead">Te ayudamos a elegir tallas, combinar prendas y coordinar la entrega. Cada pedido recibe atención personal.</p><div class="contact-grid"><div><span class="eyebrow text-olive">Escríbenos</span><h2 class="font-editorial">Un mensaje basta.</h2><p>Cuéntanos qué necesitas y te responderemos con gusto.</p><a [href]="'mailto:' + config.email" class="button-outline">{{ config.email }} ↗</a>@if (config.whatsappNumber) { <a [href]="'https://wa.me/'+config.whatsappNumber" target="_blank" rel="noopener noreferrer" class="button-dark">Conversar por WhatsApp ↗</a> }</div><div class="contact-note"><span class="eyebrow">MAISON MODE</span><p class="font-editorial">Vestir bien también se siente bien.</p><span>Lima, Perú · Atención online</span></div></div>
  <div id="preguntas" class="faq"><span class="eyebrow text-olive">Lo que necesitas saber</span><h2 class="font-editorial">Preguntas frecuentes</h2><details><summary>¿Cómo se confirma mi pedido?</summary><p>Al finalizar, WhatsApp abrirá un mensaje con tu selección. La tienda confirmará disponibilidad, entrega y monto final antes de procesarlo.</p></details><details><summary>¿El precio incluye envío?</summary><p>No. El costo de envío depende de la dirección y se confirma antes de cerrar el pedido.</p></details><details><summary>¿Cómo elijo mi talla?</summary><p>Consulta la guía de tallas en cada producto. También puedes escribirnos para recibir orientación personalizada.</p></details><details><summary>¿Puedo cambiar mi pedido?</summary><p>Mientras la tienda no lo haya confirmado, puedes editar el carrito y enviar una nueva solicitud por WhatsApp.</p></details></div>
  </section>
`, styles: [`
  .contact-page{padding-block:6rem 8rem}.contact-page h1{font-size:clamp(3.8rem,7vw,7rem);font-weight:400;letter-spacing:-.06em;line-height:1.1;margin:1rem 0 2rem}.lead{color:#6f7268;max-width:550px;line-height:1.8}.contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:3rem;margin:5rem 0 7rem}.contact-grid>div:first-child{padding:3rem 0}.contact-grid h2{font-size:2.7rem;font-weight:400;margin:.7rem 0}.contact-grid p{color:#6f7268;line-height:1.8}.contact-grid a{margin:1.5rem 1rem 0 0}.contact-note{min-height:320px;background:#6d705e;color:#fff;display:flex;flex-direction:column;justify-content:space-between;padding:3rem}.contact-note p{font-size:clamp(2.4rem,4vw,4rem);line-height:1.15;max-width:400px}.contact-note>span:last-child{font-size:.75rem}.faq{scroll-margin-top:100px;max-width:850px;margin:auto}.faq h2{font-size:3.5rem;font-weight:400;letter-spacing:-.05em;margin:.7rem 0 2rem}.faq details{border-top:1px solid #d9d5cb;padding:1.3rem 0}.faq details:last-child{border-bottom:1px solid #d9d5cb}.faq summary{cursor:pointer;display:flex;justify-content:space-between;font-size:.9rem;list-style:none}.faq summary::after{content:'+'}.faq details[open] summary::after{content:'−'}.faq details p{color:#75786e;font-size:.82rem;line-height:1.75;max-width:650px}@media(max-width:700px){.contact-page{padding-block:4rem}.contact-grid{grid-template-columns:1fr;margin:3rem 0 5rem}.contact-grid>div:first-child{padding:0}.contact-note{min-height:260px}.faq h2{font-size:2.8rem}}
`] })
export class Contact { readonly config = STORE_CONFIG; }
